# **Numpy : For Numerical Computation**


In [1]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
a.shape

(3, 5)

In [3]:
a.ndim

2

In [4]:
a.dtype.name

'int32'

In [5]:
a.itemsize

4

In [6]:
a.size

15

In [7]:
type(a)

numpy.ndarray

### **Basic operations**

In [8]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
c=a-b
print(c)

[20 29 38 47]


In [10]:
from numpy import pi
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, pi, 3)
b.dtype.name

'float64'

In [11]:
c = a + b
c

array([1.        , 2.57079633, 4.14159265])

In [12]:
# Using np.arange()
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])