# **Numpy : For Numerical Computation**


In [2]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape

(3, 5)

In [4]:
# to check the dimensions of np array
a.ndim

2

In [5]:
# to check the data type of the variable
a.dtype.name

'int32'

In [6]:
a.itemsize

4

In [7]:
a.size

15

In [8]:
type(a)

numpy.ndarray

### **Basic operations**

In [9]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
c=a-b
print(c)

[20 29 38 47]


In [10]:
# Using np.arange()
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
# Searching Numpy arrays - returns the indexes 
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [12]:
# to sort the numpy array
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]
